GPS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views
from gpsschool.views import TeacherListView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='gpsfrontend/index.html'), name='home'),
    path('about/', TemplateView.as_view(template_name='gpsfrontend/about.html'), name='about'),
    path('teachers/', TemplateView.as_view(template_name='gpsfrontend/teachers.html'), name='teachers'),
    path('gallery/', TemplateView.as_view(template_name='gpsfrontend/gallery.html'), name='gallery'),
    path('blog/', TemplateView.as_view(template_name='gpsfrontend/404.html'), name='blog'),
    path('single/', TemplateView.as_view(template_name='gpsfrontend/single.html'), name='single'),
    path('dashboard/', include('gpsschool.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('contact/', user_views.contact_view, name='contact'),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gpsschool/urls.py
from django.urls import path
from .views import (
    AnnouncementListView,
    AnnouncementDetailView,
    AnnouncementCreateView,
    AnnouncementUpdateView,
    AnnouncementDeleteView,
    UserAnnouncementListView,
    TeacherListView,
    StandardListView,
    StandardDetailView,
    StudentListView,
    StudentDetailView,
    PaymentScheduleListView
)
from . import views


urlpatterns = [
    path('', AnnouncementListView.as_view(), name='gpsschool-home'),
    path('payments/', PaymentScheduleListView.as_view(), name='payments'),
    path('students/<int:pk>/', StudentDetailView.as_view(), name='student-detail'),
    path('students/', StudentListView.as_view(), name='students'),
    path('standards/', StandardListView.as_view(), name='standards'),
    path('standards/<int:pk>/', StandardDetailView.as_view(), name='standard-detail'),
    path('user/<str:username>', UserAnnouncementListView.as_view(), name='user-announcements'),
    path('announcement/<int:pk>/', AnnouncementDetailView.as_view(), name='announcement-detail'),
    path('announcement/new/', AnnouncementCreateView.as_view(), name='announcement-create'),
    path('announcement/<int:pk>/update/', AnnouncementUpdateView.as_view(), name='announcement-update'),
    path('announcement/<int:pk>/delete/', AnnouncementDeleteView.as_view(), name='announcement-delete'),
    path('about/', views.about, name='gpsschool-about'),
    path('faculties/', TeacherListView.as_view(), name='faculty'),
]

gpsschool/models.py
from django.db import models
from django.contrib.auth.models import User
from .constants import ( SEX_CHOICES, ETHNICITY_CHOICES, COUNTRY_CHOICES,
        PAYMENT_SCHEDULES, SCHOLARSHIP_CHOICES, TASK_TYPE)
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone
import datetime
from django.db.models import Sum
from django.urls import reverse
from django.utils.translation import ugettext as _


def current_year():
    return datetime.date.today().year


def max_value_current_year(value):
    return MaxValueValidator(current_year())(value)


def year_choices():
    return [(r,r) for r in range(1984, datetime.date.today().year+1)]


class Announcement(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('announcement-detail', kwargs={'pk': self.pk})


class Location(models.Model):
    address1    = models.CharField(max_length=200)
    address2    = models.CharField(max_length=200)
    address3    = models.CharField(max_length=200)
    city        = models.CharField(max_length=200)
    state       = models.CharField(max_length=200)
    postal_code = models.CharField(max_length=10)
    country     = models.CharField(max_length=2, choices=COUNTRY_CHOICES)

    def __str__(self):
        answer = self.address1 + '\n'

        if self.address2 != None:
            answer += self.address2 + '\n'
        if self.address3 != None:
            answer += self.address3 + '\n'

        answer += self.city + ', ' + self.state + ', ' + self.postal_code + ', ' + self.country

        return answer


class School(models.Model):
    name = models.CharField(max_length=200)
    address = models.ForeignKey(Location, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    salary = models.IntegerField()
    bio = models.TextField()
    joining_date = models.DateField(auto_created=True, null=True)
    address = models.ForeignKey(Location, on_delete=models.CASCADE)
    contact_number = models.IntegerField(null=True)

    def __str__(self):
        return ("%s %s" % (self.user.first_name, self.user.last_name)).upper()


class Standard(models.Model):
    name_standard = models.CharField(max_length=120)
    class_teacher = models.ForeignKey(Teacher, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name_standard

class Subject(models.Model):
    name_subject = models.CharField(max_length=120)
    standard = models.ForeignKey(Standard, on_delete=models.CASCADE, related_name='standard_subjects', null=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='subject_teaches', null=True)

    def __str__(self):
        return  self.name_subject + " - " + self.standard.name_standard


class Book(models.Model):
    title = models.CharField(max_length=120)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='book_subject')

    def __str__(self):
        return self.title

class Payments(models.Model):
    amount = models.FloatField()
    date = models.DateField()
    comment = models.TextField(null=True)

    def __str__(self):
        return str(self.date) + ' - ' + str(self.amount)


class PaymentSchedule(models.Model):
    yearly_cost = models.FloatField(default=0)
    payment_schedule = models.CharField(max_length=2, choices=PAYMENT_SCHEDULES)
    scholarship_type = models.CharField(max_length=2, choices=SCHOLARSHIP_CHOICES, default=None)
    scholarship_amount = models.FloatField(default=0)
    transactions = models.ManyToManyField(Payments, related_name='user_transactions')


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    standard = models.ForeignKey(Standard, on_delete=models.CASCADE)
    father_name = models.CharField(null=True, max_length=120)
    mother_name = models.CharField(null=True, max_length=120)
    contact_number = models.CharField(null=True, max_length=120)
    address = models.ForeignKey(Location, on_delete=models.CASCADE, null=True)
    admission_date = models.DateTimeField(auto_now=True, editable=True)
    roll_number = models.IntegerField(default=0)
    year = models.IntegerField(_('year'), validators=[MinValueValidator(1984), max_value_current_year], null=True)
    account = models.OneToOneField(PaymentSchedule, on_delete=models.CASCADE)

    class Meta:
        ordering = ['roll_number']

    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name


class Task(models.Model):
    task_type = models.CharField(max_length=2, choices=TASK_TYPE)
    date_assigned = models.DateTimeField(blank=True)
    date_completed = models.DateTimeField(blank=True)
    score = models.FloatField(default=0)
    maximum_score = models.FloatField(default=0)
    weight = models.FloatField(default=0)
    standard = models.ForeignKey(Standard, on_delete=models.CASCADE, null=True)
    student = models.ForeignKey(Student, on_delete=models.SET_NULL, null=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True)

    def __str__(self):
        i = 0
        for x in TASK_TYPE:
            if x[0] == self.task_type:
                break
            i += 1

        return TASK_TYPE[i][1] + '-' + self.standard.name_standard

gpsschool/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.db.models import Sum
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import (
    Announcement, Teacher,
    Standard, Student,
    PaymentSchedule, Payments
)


def home(request):
    context = {
        'posts': Announcement.objects.all()
    }
    return render(request, 'gpsschool/home.html', context)
    

class PaymentScheduleListView(LoginRequiredMixin, ListView):
    model = PaymentSchedule
    context_object_name = 'payments'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        list_of_sums = [ ]
        
        qs = PaymentSchedule.objects.all()

        for q in qs:
            payments = q.transactions.all()
            sum = 0 
            for payment  in payments:
                sum += payment.amount
            list_of_sums.append(sum)

        context['fees_deposited'] = list_of_sums
        return context

class StudentListView(LoginRequiredMixin, ListView):
    model = Student
    context_object_name = 'students'


class StudentDetailView(LoginRequiredMixin, DetailView):
    model = Student
    context_object_name = 'student'


class StandardListView(LoginRequiredMixin, ListView):
    model = Standard
    context_object_name = 'standards'

class StandardDetailView(LoginRequiredMixin, DetailView):
    model = Standard
    context_object_name = 'standard'

class TeacherListView(LoginRequiredMixin, ListView):
    model = Teacher
    context_object_name = 'teachers'
    ordering = ['joining_date']
    paginate_by = 5

class AnnouncementListView(LoginRequiredMixin, ListView):
    model = Announcement
    template_name = 'gpsschool/home.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'announcements'
    ordering = ['-date_posted']
    paginate_by = 5


class UserAnnouncementListView(ListView):
    model = Announcement
    template_name = 'gpsschool/user_announcements.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'announcements'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Announcement.objects.filter(author=user).order_by('-date_posted')


class AnnouncementDetailView(DetailView):
    model = Announcement


class AnnouncementCreateView(LoginRequiredMixin, CreateView):
    model = Announcement
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class AnnouncementUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Announcement
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        announcement = self.get_object()
        if self.request.user == announcement.author:
            return True
        return False


class AnnouncementDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Announcement
    success_url = '/dashboard/'

    def test_func(self):
        announcement = self.get_object()
        if self.request.user == announcement.author:
            return True
        return False


def about(request):
    return render(request, 'gpsschool/about.html', {'title': 'About'})

templates/gpsschool/about.html
{% extends "gpsschool/base.html" %}
{% block content %}
<h3 style="color: blue;">About Dashboard</h3>
<div class="container">
	<p>This is the dashboard of our school which is mostly used by our teachers, parents, students etc. We will make all important announcements here. We will also announce results and transcripts etc. on our dashboard. Our administrators will sync with our webmaster to ensure smooth and timely updates on our website.</p>
</div>
{% endblock content %}

templates/gpsschool/announcement_confirm_delete.html
{% extends "gpsschool/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Announcement</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'announcement-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

templates/gpsschool/announcement_detail.html
{% extends "gpsschool/base.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="#">{{ object.author }}</a>
        <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
        {% if object.author == user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'announcement-update' object.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'announcement-delete' object.id %}">Delete</a>
          </div>
        {% endif %}
      </div>
      <h4 class="article-title">{{ object.title }}</h4>
      <p class="article-content">{{ object.content }}</p>
    </div>
  </article>
{% endblock content %}

templates/gpsschool/announcement_form.html
{% extends "gpsschool/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">New Announcement</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/gpsschool/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'gpsschool/css/main.css' %}">

    {% if title %}
        <title>GPS Dashboard - {{ title }}</title>
    {% else %}
        <title>GPS Dashboard</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'gpsschool-home' %}">GPS Dashboard</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'gpsschool-home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'gpsschool-about' %}">About</a>
              <a class="nav-item nav-link" href="{% url 'faculty' %}">Teachers</a>
              <a class="nav-item nav-link" href="{% url 'standards' %}">Standards</a>
              <a class="nav-item nav-link" href="{% url 'students' %}">Students</a>
              <a class="nav-item nav-link" href="{% url 'payments' %}"> {% if request.user.is_superuser %} Fees Payment {% endif %}</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'announcement-create' %}">New Announcement</a>
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
</body>
</html>

templates/gpsschool/home.html
{% extends "gpsschool/base.html" %}
{% block content %}
    {% for announcement in announcements %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ announcement.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-announcements' announcement.author.username %}">{{ announcement.author }}</a>
              <small class="text-muted">{{ announcement.date_posted|date:"F d, Y" }}</small>
            </div>
            <h4><a class="article-title" href="{% url 'announcement-detail' announcement.id %}">{{ announcement.title }}</a></h4>
            <p class="article-content">{{ announcement.content }}</p>
          </div>
        </article>
    {% endfor %}

    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
    
{% endblock content %}

templates/gpsschool/standard_detail.html
{% extends "gpsschool/base.html" %}

	<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">

    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
 -->
{% block content %}
	<div class="container">
		<h3>Standard: {{ standard }}</h3>
		<h5>Class Teacher: {{ standard.class_teacher }}</h5>
		<table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
		  <thead>
		    <tr>
		      <th scope="th-sm">Roll Number</th>
		      <th scope="th-sm">Full Name</th>
		      <th scope="th-sm">Father Name</th>
		      <th scope="th-sm">Contact Number</th>
		    </tr>
		  </thead>
		  <tbody>

		{% for student in standard.student_set.all %}
		    <tr>
		      <th scope="row">{{student.roll_number}}</th>
		      <td>{{ student.user.first_name }} {{ student.user.last_name }}</td>
		      <td>{{ student.father_name }}</td>
		      <td>{{ student.contact_number }}</td>
		    </tr>
		{% endfor %}

		  </tbody>
		</table>
	</div>

	<script type="text/javascript">
		$(document).ready(function() {
            $('#dtBasicExample').DataTable();
        } );
	</script>
     
{% endblock content %}

templates/gpsschool/standard_list.html
{% extends "gpsschool/base.html" %}
{% block content %}

		{% for standard in standards %}

			<div class="list-group">
				<a href="{% url 'standard-detail' standard.id %}" class="list-group-item list-group-item-action"> {{ standard }}</a>
			</div>

		{% endfor %}

{% endblock content %}

templates/gpsschool/student_detail.html
{% extends "gpsschool/base.html" %}
{% block content %}

	<div class="container">
	    <div class="row">
	        <div class="col">
	            <div class="card">
	                <div class="card-body">
	                    <div class="row">
	                        <div class="col-12 col-lg-8 col-md-6">
	                            <h3 class="mb-0 text-truncated">{{ student.user.first_name }} 
	                            {{student.user.last_name }}</h3>
	                            <p class="lead"> Standard {{ student.standard }} and  
	                            Roll Number {{ student.roll_number }}</p>
	                            <p>
	                                I love to read, hang out with friends, watch football, listen to music, and learn new things.
	                            </p>
	                        	<p>
	                            	{% for subject in student.standard.standard_subjects.all %}
	                            		<span class="badge badge-info tags">{{ subject }}</span>
	                            	{% endfor %}
	                            </p>
	                            <p><strong>Father's Name:</strong> {{ student.father_name }}</p>
	                            <p><strong>Mother's Name:</strong> {{ student.mother_name }}</p>
	                            <p><strong>Contact Number:</strong> {{ student.contact_number }}</p>
	                            <p><strong>Address:</strong> {{ student.address }}</p>
	                            <p><strong>Current Year:</strong> {{ student.year }}</p>

	                        </div>
	                        <div class="col-12 col-lg-4 col-md-6 text-center">
	                            <img src="{{ student.user.profile.image.url }}" alt="" class="mx-auto rounded-circle img-fluid">
	                            <br>
	                            <ul class="list-inline ratings text-center" title="Ratings">
	                                <li class="list-inline-item"><a href="#"><span class="fa fa-star"></span></a>
	                                </li>
	                                <li class="list-inline-item"><a href="#"><span class="fa fa-star"></span></a>
	                                </li>
	                                <li class="list-inline-item"><a href="#"><span class="fa fa-star"></span></a>
	                                </li>
	                                <li class="list-inline-item"><a href="#"><span class="fa fa-star"></span></a>
	                                </li>
	                                <li class="list-inline-item"><a href="#"><span class="fa fa-star"></span></a>
	                                </li>
	                            </ul>
	                        </div>

	                        <div class="container"> <!-- Container for payment history starts here.-->
		                        <div class="panel-group" id="accordion">

								  <div class="panel panel-default">
								    <div class="panel-heading">
								      <h4 class="panel-title">
								        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
								        	Fees Payment History
								        </a>
								      </h4>
								    </div>

								    {% if request.user.is_superuser %}

								    <div id="collapseThree" class="panel-collapse collapse">
								      <div class="panel-body">
								      	<h5>Total amount to be paid(INR): {{ student.account.yearly_cost}}</h5>
								      	<hr>
								      		<div class="container">
												  <h5>List of transactions</h2>            
												  <table class="table table-bordered">
												    <thead>
												      <tr>
												        <th>Date</th>
												        <th>Amount</th>
												        <th>Comment</th>
												      </tr>
												    </thead>
												    <tbody>

												    {% for transaction in student.account.transactions.all %}
												      <tr>
												        <td>{{ transaction.date }}</td>
												        <td>{{ transaction.amount }}</td>
												        <td>{{ transaction.comment }}</td>
												      </tr>
												    {% endfor %}
												    </tbody>
												  </table>
												</div>
											</div>
								    </div>
								    {% endif %}

								  </div>

								</div>
							</div> <!-- Container for payment history ends here -->

							<div class="container">
								<h5>Progress Report</h5>

								<div class="container"><hr>

									{% for mark in student.task_set.all %}
										<p>{{ mark.subject.name_subject }} {{ mark.task_type }} : {{ mark.score }} out of {{ mark.maximum_score }}</p>
									{% endfor %}

								</div>
							
							</div>

	                    </div>
	  	                    <!--/row-->
	                </div>
	                <!--/card-block-->
	            </div>
	        </div>
	    </div>
	</div>

{% endblock content %}